import type { Metadata } from "next";
import "./globals.css";
import { ThreeModelProvider } from "@/context/ThreeModelContext";
import { Header } from "@/components/ui/organisms/Header";
import { HeaderWrapper } from "@/components/ui/molecules/HeaderWrapper";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "MEMOI Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative w-full h-full">
      <body
        className="relative"
        cz-shortcut-listen="true"
      >
        <ReactQueryProvider>
          <ThreeModelProvider>

            <HeaderWrapper>
              <Header />
            </HeaderWrapper>

            {/* <main className="relative"> */}
            {/* <Suspense fallback={<LoadingPage />}> */}
            {children}
            {/* </Suspense> */}
            {/* </main> */}
            {/* <Footer /> */}

          </ThreeModelProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
